### ISSUE TITLE
[FEATURE] Change UI of add project page.

### ISSUE THREAD

**Issue by munnokd** [lewisushindi/Projest#129]
### Description

Right now add project page is good but it need some excellent UI.

### Describe the solution you'd like

If anyone is interested in this work on this issue and improving UI.

**Comment by Mrigakshi-RC** [comment]
Can we have something like these @munnokd :
![image](https://github.com/Frenziecodes/Projest/assets/95232525/95e3acf9-7b4f-483a-b2da-ccada1efa596)
![image](https://github.com/Frenziecodes/Projest/assets/95232525/fc499f0a-0b16-4554-949c-da8f8a8f091e)

**Comment by munnokd** [comment]
Ya, why not.  I assign this issue to you.

**Comment by Mrigakshi-RC** [comment]
Opened a PR for the same.

**Comment by munnokd** [comment]
> Opened a PR for the same.

Great. Is this responsive or not?

**Comment by Mrigakshi-RC** [comment]
No it's not responsive for mobile, will make it responsive then

**Comment by munnokd** [comment]
Hey why you closed that pr?

**Comment by Mrigakshi-RC** [comment]
Because my code didn't make it responsive. I'm currently making it responsive on another branch and almost done.

**Comment by munnokd** [comment]
> Because my code didn't make it responsive. I'm currently making it responsive on another branch and almost done.

Okay no problem.

**Comment by Mrigakshi-RC** [comment]
Hey, opened a new PR, please do review, thanks.

**Comment by Frenziecodes** [comment]
completed by @Mrigakshi-RC
