### ISSUE TITLE
re-style the view projects page

### ISSUE THREAD

**Issue by lewisushindi** [lewisushindi/Projest#19]

**Comment by Vee339** [comment]
Hi, I hope you are doing well. 
I want to restyle the project page of this web app. Please provide me more info.

**Comment by lewisushindi** [comment]
hi @Vee339 , I want to change the projects display from flexbox to grid in my view projects page. I have a div with an id projectContainer that is responsible for styling the projects display. replace the properties related to the flexbox layout with properties related to the grid layout. Should be responsive to all devices.

**Comment by martindevelopske** [comment]
Can I please take over this one?

**Comment by lewisushindi** [comment]
#24 solved this  issue

**Comment by lewisushindi** [comment]
@martindevelopske yes and can you make it responsive to all devices , kindly

**Comment by lewisushindi** [comment]
@Vee339  Hi, it was not responsive to all devices. That's the reason I reverted the changes. Can you work on that ?

**Comment by Vee339** [comment]
> 

Yes, sure. I can work on this.

**Comment by lewisushindi** [comment]
@Vee339 okay. You can work on that. Happy contributions

**Comment by lewisushindi** [comment]
completed by @Vee339 solved using pull request #33
