### ISSUE TITLE
Add projects

### ISSUE THREAD

**Issue by lewisushindi** [lewisushindi/Projest#20]
visit the add project page , and fill the form to add your project

**Comment by munnokd** [comment]
I added my project to your website😊😊.

**Comment by Fax-ofJax** [comment]
I have added my project as well. As i am new to open source contributions, i request the admin to guide me to make my first contribution (if possible). You can check my project if you have any doubts regarding my skills, you can checkout my project as well. I have a decent knowledge in my field and you just have to guide me in the right direction. Looking forward to get a reply from you. (You can also assign me a work if some of the assignee's are just hibernating)

**Comment by lewisushindi** [comment]
Hello @Fax-ofJax,
Thank you for submitting your project and showing interest in contributing to our open source project! We're excited to have you join our community. To get started, I suggest taking a look at our project's issue tracker on GitHub. This will give you an idea of the current tasks that require attention. If you find something that interests you, feel free to assign yourself to the task and start working on it. Alternatively, you can browse the site and see if there are any features you'd like to see added or any existing bugs that need to be fixed. If you come across any issues, please feel free to open a new issue.
Once again, thank you for your interest in contributing, and we're looking forward to seeing your contributions!

**Comment by harisdev-netizen** [comment]
Hey @lewisushindi  can you assign it to me?

**Comment by lewisushindi** [comment]
Hey @harisdev-netizen  sure you can add your project visit [projest](https://projest-290c8.web.app/addproject)
