### ISSUE TITLE
[BUG] Tags Not Sending to Firebase Database

### ISSUE THREAD

**Issue by lewisushindi** [lewisushindi/Projest#22]
I'm having an issue with the tags not being sent to the Firebase database. When I try to view the project details on the "View Project" page, the tags are not being displayed and are instead showing as "undefined." I believe the problem is in the code for sending the tags to the database, but I'm not sure how to resolve it. Can someone help me figure out what's going wrong and how to fix it? Thank you in advance!

**Comment by sohamtembhurne** [comment]
I have sent a pull request regarding this issue. The values for the label tags were wrong. Also, the boolean condition to check the checkbox was incorrect. Let me know if you face any problems.

**Comment by lewisushindi** [comment]
Thank you sir ! Reviewed and merged.
