### ISSUE TITLE
[BUG] Enhance the hover effect of button

### ISSUE THREAD

**Issue by anikdhabal** [lewisushindi/Projest#28]
**Describe the bug**
Button is not clearly visible when mouse-hover it.

**To Reproduce**
1. Go to PROJEST
2.Mouse hover on the button

**Expected behavior**
Button should be visible at the time hover. Hover Effect style have to change.

**Screenshots**
<img width="1080" alt="Screenshot 2023-02-06 175402" src="https://user-images.githubusercontent.com/81948346/216971728-e6d4cc4c-37a1-4fd5-a672-7a353f8337ce.png">

**Comment by lewisushindi** [comment]
canyou work on that sir?

**Comment by anikdhabal** [comment]
yes ,sure

**Comment by lewisushindi** [comment]
assigned it to you. Happy contributions sir!
