### ISSUE TITLE
User login.

### ISSUE THREAD

**Issue by E-fais** [lewisushindi/Projest#35]
Before adding a new project, user must be signed in with github profile to avoid spam.

**Comment by lewisushindi** [comment]
Thank you for raising this issue, and for your suggestion to require users to be signed in with their GitHub profile before adding a new project. I appreciate your input and will definitely  implement this as a feature. In the meantime, I'll continue to monitor for any spam submissions and take appropriate action. Please feel free to reach out if you have any further suggestions or feedback.

**Comment by anikdhabal** [comment]
hey @lewisushindi  can I work on this?

**Comment by lewisushindi** [comment]
@anikdhabal  yeah sure! Happy contributions sir!

**Comment by lewisushindi** [comment]
switched to issue #65
