### ISSUE TITLE
Confirm message for users

### ISSUE THREAD

**Issue by E-fais** [lewisushindi/Projest#36]
After adding necessary details and click on add project button, there is no confirmation message given to users. This may confuse users, and users may add same projects again. So please give a confirmation message to users when the project is added successfully.

**Comment by lewisushindi** [comment]
Thank you for bringing this to our attention, and for your suggestion to add a confirmation message for users when they successfully add a project. We completely agree that this would be a helpful feature for our users, and we'll prioritize implementing it as soon as possible.

**Comment by E-fais** [comment]
You are welcome 👍 .

**Comment by ELFrancisco4** [comment]
Hi. Which specific file has the issue so it can be tackled?
