### ISSUE TITLE
Security Issue

### ISSUE THREAD

**Issue by ELFrancisco4** [lewisushindi/Projest#37]
Firebase configuration credentials are hard coded in the addproject.html file.
That could be a huge security concern.

Best practice is to make use of environment variables created within the .env file and accessed using the process.env API.

![Screenshot (347)](https://user-images.githubusercontent.com/72754647/221380943-215e399b-3972-46ac-aac9-0c778e97da1b.png)

**Comment by lewisushindi** [comment]
@ELFrancisco4 Hello,

Thank you for bringing this to our attention. We appreciate your concern about the security of our project.

You are correct that hard coding sensitive credentials like Firebase configuration information in a file is not a best practice. We take security seriously and we want to ensure that our project is as secure as possible.

We will look into implementing the use of environment variables created within the .env file and accessed using the process.env API, as you suggested. This is a best practice for securing sensitive information, and we want to make sure we are following it.

Thank you again for your input, and please let us know if you have any other suggestions or concerns.

**Comment by ELFrancisco4** [comment]
You are most welcome. Happy to help

**Comment by Vishal21121** [comment]
Is this issue still open? I can help you in this.

**Comment by lewisushindi** [comment]
@Vishal21121 yeah its still open. I've assigned it to you. Happy contributions sir!

**Comment by Vishal21121** [comment]
Thank you for assigning this issue to me but as this project is using vanilla js so it's not possible to use dotenv package over here. API key and other security related stuff can be added directly in the deployment environment hope it helps.
