### ISSUE TITLE
[BUG] Back to the top(Arrow icon) is hidden by the footer

### ISSUE THREAD

**Issue by anikdhabal** [lewisushindi/Projest#41]
**Describe the bug**
Back to the top(Arrow icon) is hidden by the footer in Docs page.

**To Reproduce**
1. Go to Docs
2. Scroll down to footer
3. See error

**Expected behavior**
arrow function color should not be similar to the footer color.

**Screenshots**
![9bi8wq0v](https://user-images.githubusercontent.com/81948346/222917947-bb8a9818-bf84-4f3c-ab53-e770f8e0441d.png)

**Comment by lewisushindi** [comment]
@anikdhabal Thank you for raising this issue. Am working on it right away.

**Comment by lewisushindi** [comment]
Solved using  https://github.com/lewisushindi/Projest/commit/b867661ec2be58088e5fb8e179dd2062f8046ecc
