### ISSUE TITLE
[BUG]Make Projest text clickable

### ISSUE THREAD

**Issue by anikdhabal** [lewisushindi/Projest#42]
**Describe the bug**
When someone click the projest text it redirects the user to Homepage.

**To Reproduce**
1. Go to PROJEST
2. Click on PROJEST text in the page
3. See error

![typ3vpdi](https://user-images.githubusercontent.com/81948346/222977604-2d5aa98c-78de-49c4-b0ad-ed30f434746b.png)

**Comment by anikdhabal** [comment]
can I work  on it?

**Comment by lewisushindi** [comment]
Yes @anikdhabal you can work on it
