### ISSUE TITLE
[BUG] PROJEST text is not visible on hover

### ISSUE THREAD

**Issue by anikdhabal** [lewisushindi/Projest#45]
**Describe the bug**
PROJEST text is not visible on hover

**To Reproduce**

**Expected behavior**

**Screenshots**
<img width="1071" alt="Screenshot 2023-03-10 235030" src="https://user-images.githubusercontent.com/81948346/224392797-a6ff285c-e74f-43ea-8171-4533d5ab8071.png">

**Comment by Vijaykv5** [comment]
I'm Working on this Issue ..Please Assign me

**Comment by lewisushindi** [comment]
Thanks for your contribution! @Vijaykv5
