### ISSUE TITLE
[BUG]Nav Menu is not clickable from add project page in small screen

### ISSUE THREAD

**Issue by anikdhabal** [lewisushindi/Projest#47]
**Describe the bug**
Nav Menu is not clickable from add project page.

**To Reproduce**
1. Go to Projest
2. Click on Projects
3.open Add project
4. click nav menu

**Expected behavior**
it should working.

**Screenshots**
<img width="362" alt="Screenshot 2023-03-11 234232" src="https://user-images.githubusercontent.com/81948346/224504787-2b16f400-5fe9-48ba-a3a2-496b6046ee75.png">

**Comment by Vijaykv5** [comment]
Working on this Issue

**Comment by lewisushindi** [comment]
fixed
