### ISSUE TITLE
[BUG]Submit button is touching the Browser frame

### ISSUE THREAD

**Issue by anikdhabal** [lewisushindi/Projest#50]
**Describe the bug**
Submit button is touching the Browser frame in small screen.

**Screenshots**
<img width="419" alt="Screenshot 2023-03-13 232041" src="https://user-images.githubusercontent.com/81948346/224785001-8ac30cef-e253-42ce-9be3-d61ab6e4239b.png">

**Comment by lewisushindi** [comment]
Okay! ill be working on this as soon as possible, currently we are switching the project to react. Am waiting for that to be completed so that I can work on this issue!

**Comment by lewisushindi** [comment]
fixed
