### ISSUE TITLE
[BUG] Web design bug on Opera browser

### ISSUE THREAD

**Issue by gabrysia694** [lewisushindi/Projest#53]
**Describe the bug**
The design appears to be a bit messy when viewed on the Opera browser.

**To Reproduce**
1. Go to 'Docs'

**Expected behavior**
Misaligned 'Notes' paragraph compared to others. Further content of the 'Docs' page is compressed leaving white space on the side in 'Frequently asked questions' and 'Glossary of terms'. Similar excessive white space on the side is also noticeable in 'Home' page and 'Add Project'.

**Screenshots**
<img width="910" alt="bug" src="https://user-images.githubusercontent.com/97764356/225112769-80e7d68d-a0c0-4c5b-8974-774116a045b6.png">

<img width="917" alt="bug3" src="https://user-images.githubusercontent.com/97764356/225112923-dc7c476c-c4fd-42ab-8e51-794e65558e1f.png">

<img width="928" alt="bug4" src="https://user-images.githubusercontent.com/97764356/225112995-c624cc0e-0f1e-4cec-8d04-e3b05d4e3198.png">

**Comment by lewisushindi** [comment]
Dear @gabrysia97, we appreciate you for bringing this matter to our attention. We are currently in the process of transitioning the project to React, and once that is completed, we will be able to start working on this. Thank you for your patience and understanding!

**Comment by lewisushindi** [comment]
We have completed the transition of the project to React, and it appears that the issue has been resolved. Would you kindly take a moment to visit [Projest](https://projest-290c8.web.app/) and confirm that the design displays properly on the Opera browser?

**Comment by gabrysia694** [comment]
Yes, the design displays properly on the Opera browser now. However, I found another small design bug. Project tags could be wider to fully show the text; currently Typescript and Tailwind.css are cut off. There's a capital "I" in Project GIthub Link too. Should I open a new issue on this one?

![obraz_2023-04-10_123007651](https://user-images.githubusercontent.com/97764356/230884988-e88049d4-5d19-4a2b-acad-0ed29258abeb.png)

**Comment by lewisushindi** [comment]
Thanks for letting me know, @gabrysia694 . I'm glad to hear that the design is displaying properly on Opera now.  I have just fixed the design bug you mentioned. Project tags now display the full text, and the capitalization issue in 'Project Github Link' has been corrected. Please let me know if you encounter any other issues, and thanks again for helping improve our platform!
