### ISSUE TITLE
ADDING OF EMPTY PROJECTS POSSIBLE

### ISSUE THREAD

**Issue by therealtmmy** [lewisushindi/Projest#55]
When you click on submit button on the project section, you should recieve a notification that would request you to fill all those input fields compulsorily. 
- Note: Obviously now, users can add empty projects. This is wrong

**Comment by lewisushindi** [comment]
thanks @therealtmmy that's a great idea. Currently we are switching the project to react, i will get back and work on this when that is done.

**Comment by lewisushindi** [comment]
Hi @therealtmmy, I wanted to let you know that we have finished transitioning the project to React. I was wondering if we could discuss the best implementation method to prevent the addition of empty projects?

**Comment by E-fais** [comment]
Hey @lewisushindi ,
can i try to work on this..

**Comment by lewisushindi** [comment]
Hey @E-fais  I have assigned you the issue

**Comment by lewisushindi** [comment]
@therealtmmy okay I have assigned the issue to  @E-fais

**Comment by E-fais** [comment]
> Can u assign this to me also

@lewisushindi ,
I have already worked in this project. I think it should be better to give chance to more people, if @Mudassirkhan2 is available , please assign this to him.

**Comment by lewisushindi** [comment]
Hey @Mudassirkhan2 are you still available ? Am assigning you the issue

**Comment by lewisushindi** [comment]
@E-fais okay assigned the issue to @Mudassirkhan2

**Comment by Mudassirkhan2** [comment]
yes

**Comment by lewisushindi** [comment]
Thank you @Mudassirkhan2
