### ISSUE TITLE
[BUG] Footer is not in Correct Position

### ISSUE THREAD

**Issue by anikdhabal** [lewisushindi/Projest#57]
**Describe the bug**
In the contribution page Footer position is wrong.

**Screenshots**
<img width="1080" alt="Screenshot 2023-03-23 225612" src="https://user-images.githubusercontent.com/81948346/227286183-24945207-695e-4bc0-b54b-e512a635aeac.png">

**Comment by Palakkgoyal** [comment]
Can you please elaborate as I want to work on this issue.

**Comment by RLTek** [comment]
I believe it is just the end of the contributing page. Adding either more content or making the text appear bigger on bigger screens would help fill out the screen more. It looks fine on mobile.

**Comment by lewisushindi** [comment]
completed visit [projest](https://projest-290c8.web.app/)
