### ISSUE TITLE
[FEATURE]: Use new yml forms for Issues

### ISSUE THREAD

**Issue by kumarsonsoff3** [lewisushindi/Projest#61]
**Is your feature request related to a problem? Please describe.**
Markdown templates are now an old type of GitHub issue templates. Most of the new and advanced projects on GitHub now uses the `yml` form for issue. 

**Describe the solution you'd like**
We can also use the new GitHub issue forms to `Projest`. This is how those forms look like.
![image](https://user-images.githubusercontent.com/88786642/227740704-c707d95d-6436-423c-9cd1-b58000787c8a.png)

**Additional context**
I'd love to work on this issue though.

**Comment by lewisushindi** [comment]
@kumarsonsoff3 can i assign this issue to you ?

**Comment by kumarsonsoff3** [comment]
Yeah, Sure! Would love to work on this! :rocket:

**Comment by lewisushindi** [comment]
okay  @kumarsonsoff3  I have assigned the issue to you
