### ISSUE TITLE
[FEATURE]: Adding an editing + Login Feature in the section of "Projects"

### ISSUE THREAD

**Issue by Fax-ofJax** [lewisushindi/Projest#65]
**Is your feature request related to a problem? Please describe.**
I had submitted my project on the website yesterday. It happens to be that the project name which I had given was of a different project and the details i had filled-in was of another one.  When i searched for an editing option to change the name of it, i cannot find one and the flaw was permanent. 

**Describe the solution you'd like**
So, I would like to add an editing feature to this section of projects. It's also safe that a login system can be made in-order to keep the data safe and this makes sure that those who have logged in can only edit their projects and not of others. This ensures credibility and preventing misuse of other people's data.

**Additional context**
I would like to work upon this issue if the Project is switched to react

**Comment by Fax-ofJax** [comment]
@lewisushindi please do provide your view regarding this issue and update me when the code is switched to react!

**Comment by Fax-ofJax** [comment]
Yeah sure. Thanks for assigning me this issue. Looking forward to contribute!✌️

**Comment by lewisushindi** [comment]
@Fax-ofJax we have done switching the project to react.js . we can start working on this issue

**Comment by Fax-ofJax** [comment]
Hello @lewisushindi. Sorry for replying late! So, what can we use for backend to store the data's?

**Comment by lewisushindi** [comment]
@Fax-ofJax , which labels would you like me to add to this issue? Let me know and I'll make sure they are added for you.

**Comment by lewisushindi** [comment]
@Fax-ofJax Do you still want to work on the editting feature ?

**Comment by Fax-ofJax** [comment]
Sorry for being inactive for the past few weeks. I would like to work upon this project, but I will continue to remain offline till this month end. So if u are flexible, we can work together by starting of next month or feel free to reassign this issue to someone else. (I will be willing to work upon this issue if not for my exams)
