### ISSUE TITLE
footer position on mobile version

### ISSUE THREAD

**Issue by lewisushindi** [lewisushindi/Projest#69]
on the mobile version of the view projects page . the footer is not positioned at the bottom.
![Screenshot (201)](https://user-images.githubusercontent.com/104835999/230777788-45cba820-b62c-4164-b7a2-c2098481156b.png)

**Comment by pushkaraj2007** [comment]
I would like to work on this issue.

Can you please assign me?

**Comment by lewisushindi** [comment]
okay sure @pushkaraj2007

**Comment by pushkaraj2007** [comment]
Thanks, @lewisushindi 

I'll soon start working on this issue...

**Comment by lewisushindi** [comment]
Awesome, @pushkaraj2007 ! Looking forward to seeing your progress.

**Comment by harisdev-netizen** [comment]
The footer seems to be not perfect on web view. If anyone isn't working on this kindly do assign it to me.

**Comment by pushkaraj2007** [comment]
I think this issue has been resolved. 

Of you are still facing this issue can you please explain a bit more where the footer position is not correct. 

Like on which viewport?

**Comment by harisdev-netizen** [comment]
I don't thing it has been resolve. I mean it might be for mobile version but in web version it doesn't seem to be resolved.

![image](https://user-images.githubusercontent.com/81189198/231102247-7af40c6a-44de-439c-b797-3ac1dc6efea4.png)

Shouldn't the footer be at the end of the web page?

**Comment by pushkaraj2007** [comment]
@harisdev-netizen 

You are right on the add project and contributing page it is still issue.

Thanks for informing, I'll soon make a PR that resolves this issue.
