### ISSUE TITLE
Make the Navbar responsive

### ISSUE THREAD

**Issue by lewisushindi** [lewisushindi/Projest#7]
The navbar links should switch to a hamburger menu  from tablet size and below.

**Comment by Jordan-Gallivan** [comment]
Hello! I'm just getting my feet wet in open source and would like to help you on this issue.  

I've used something similar to this ( https://www.w3schools.com/howto/tryit.asp?filename=tryhow_js_topnav )  for my blog.  Is this what you're looking for?

**Comment by lewisushindi** [comment]
@Jordan-Gallivan  yes that's what am looking for. I've assigned you the issue .Happy contributions !

**Comment by Jordan-Gallivan** [comment]
@lewisushindi My pull request has been submitted.  Please let me know if this is satisfactory and if you need my help on anything else!

Thank you for letting me work on this.  I'm happy to help with further issues pertaining to the webpage.

**Comment by lewisushindi** [comment]
Thank you for your contribution!
