### ISSUE TITLE
[DESIGN]: Change design of docs page

### ISSUE THREAD

**Issue by munnokd** [lewisushindi/Projest#73]
In docs page UI is not good you able to see that in below image.

![image](https://user-images.githubusercontent.com/81804004/231133228-b3d8fe27-c9c1-4cc7-855f-b3381a6521cc.png)

If any body wanted to change the UI of docs page so please go ahead.

**Comment by Sahad-09** [comment]
Assign it to me, I would like to contribute

**Comment by Mudassirkhan2** [comment]
Can you assign this to me

**Comment by Mudassirkhan2** [comment]
Ok

**Comment by munnokd** [comment]
Hey, @Mudassirkhan2  I assigned this issue to you. You can start work on this.

**Comment by Mudassirkhan2** [comment]
> Hey, @Mudassirkhan2 I assigned this issue to you. You can start work on this.

can you discribe how exactly you want docs UI to look like ?
