### ISSUE TITLE
new feature

### ISSUE THREAD

**Issue by rajeshmn47** [lewisushindi/Projest#77]
create feature of likes

**Comment by lewisushindi** [comment]
Hello @rajeshmn47, the idea of adding a "like" feature sounds great. However, I suggest that we prioritize the implementation of the login feature before working on the "like" feature. Do you think there's any other way we can implement the "like" feature without having the login feature first?

**Comment by munnokd** [comment]
@rajeshmn47  Thank you for the suggest this issue. Once #65 issue will be done then we assign this issue to you or any other who wanted to work on this issue.

**Comment by lewisushindi** [comment]
@rajeshmn47 we are almost completing the implementation of the registration and login feature, just some styling remaining and little changes on the site . Then we can start implementing this

**Comment by rajeshmn47** [comment]
ok

**Comment by rajeshmn47** [comment]
ok
