### ISSUE TITLE
form data getting submitted issue

### ISSUE THREAD

**Issue by 777Prabhjot** [lewisushindi/Projest#79]
### Description

In add project page form data is getting submitted even if inputs are empty i think save project button should be disabled until we insert value inside form inputs.

**Screen Shot**
<img width="910" alt="Screenshot 2023-04-15 181411" src="https://user-images.githubusercontent.com/68184118/232224509-2b16b28f-4d10-4fa3-a5ed-d290ef990a8c.png">

**Comment by lewisushindi** [comment]
@777Prabhjot I have assigned you the issue

**Comment by 777Prabhjot** [comment]
@lewisushindi it's working properly in local server i think your latest code is not uploaded on vercel

**Comment by munnokd** [comment]
@777Prabhjot Okay I will deploy latest code

**Comment by lewisushindi** [comment]
@munnokd I've already deployed [projest](https://projest.vercel.app/)

**Comment by lewisushindi** [comment]
@777Prabhjot right! Now its working correctly [projest](https://projest.vercel.app/)
