### ISSUE TITLE
Clicking on every other project tag - first tag getting selected

### ISSUE THREAD

**Issue by SoundaryaKoutharapu** [lewisushindi/Projest#80]
### Description

Steps to reproduce the bug:
1. open Projest
2. Go to projects
3. Click on add project 
4. Click on python/java ...etc on any other tags
    java script tag getting selected

https://user-images.githubusercontent.com/71914071/232505949-df4069c2-f5b2-40f0-857a-0875fedbf9ec.mp4

**Comment by lewisushindi** [comment]
Could you please verify if the latest changes have resolved the error in [projest](https://projest.vercel.app/), @SoundaryaKoutharapu? Thank you.

**Comment by SoundaryaKoutharapu** [comment]
The issue still exits.
I guess, that is due to same the naming of 'for=" ' .
If you could assign this to me, I would like to work on this

**Comment by SoundaryaKoutharapu** [comment]
> Could you please verify if the latest changes have resolved the error in [projest](https://projest.vercel.app/), @SoundaryaKoutharapu? Thank you.

Yeah, the issue still exists.

**Comment by lewisushindi** [comment]
@SoundaryaKoutharapu  Done fixing the issue. Thanks
