### ISSUE TITLE
[FEATURE] :login feature

### ISSUE THREAD

**Issue by rajeshmn47** [lewisushindi/Projest#81]
### Description

login feature

### Describe the solution you'd like

to add like feature we need login.so i would work on login first

**Comment by lewisushindi** [comment]
All right, @rajeshmn47, I have assigned the login implementation issue to you

**Comment by rajeshmn47** [comment]
i am setting login using redux

**Comment by rajeshmn47** [comment]
can u configure firebase signup and auth?

**Comment by lewisushindi** [comment]
@rajeshmn47 i've enabled Email/password authentication and Github authentication

**Comment by lewisushindi** [comment]
I've added the basic registration form structure , currently after registration the user is redirected to viewprojects page .. Once the Login page is done i'll change that

**Comment by lewisushindi** [comment]
completed, Just some  styling needed
