### ISSUE TITLE
i think pagination should be implemented

### ISSUE THREAD

**Issue by 777Prabhjot** [lewisushindi/Projest#84]
### What would you like to share?

In the view projects page pagination should be there because as the more projects will got added only number of projects should available for a page.

**Screen shot**

<img width="948" alt="Screenshot 2023-04-24 155409" src="https://user-images.githubusercontent.com/68184118/233970818-6c8b3994-d1c1-4289-b54e-670b5fff767c.png">

**Comment by lewisushindi** [comment]
okay @777Prabhjot Go ahead, implementing pagination is a great idea
