### ISSUE TITLE
skill tags input should be changed

### ISSUE THREAD

**Issue by 777Prabhjot** [lewisushindi/Projest#91]
### What would you like to share?

In add project page i think skills should be added as follow:-
<img width="493" alt="Screenshot 2023-04-27 171658" src="https://user-images.githubusercontent.com/68184118/234853018-3252418e-f608-49d1-80c8-3dd11173157f.png">

because in this check input method
<img width="319" alt="Screenshot 2023-04-27 171710" src="https://user-images.githubusercontent.com/68184118/234853074-febfc877-bcc9-4de9-9cb7-916a79535672.png">

user can only select the given tags but through the above skills adding method user can just type the tag they want to put and that can be added or removed easy it will be a great user experience.

**Comment by lewisushindi** [comment]
@777Prabhjot  Go ahead and kindly switch to [React-App](https://github.com/lewisushindi/Projest/tree/React-App) branch coz am doing some changes to the ui

**Comment by lewisushindi** [comment]
okay just make the necessary changes and submit to the master branch.  Demo login details ; 
Email: `test@gmail.com`
Password:`123456`
